package com.cmcc.migutvtwo.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.cmcc.migutvtwo.dao.SearchHistory;
import com.cmcc.migutvtwo.dao.History;
import com.cmcc.migutvtwo.dao.Favorite;
import com.cmcc.migutvtwo.dao.LiveAlert;
import com.cmcc.migutvtwo.dao.PlayMemory;

import com.cmcc.migutvtwo.dao.SearchHistoryDao;
import com.cmcc.migutvtwo.dao.HistoryDao;
import com.cmcc.migutvtwo.dao.FavoriteDao;
import com.cmcc.migutvtwo.dao.LiveAlertDao;
import com.cmcc.migutvtwo.dao.PlayMemoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig searchHistoryDaoConfig;
    private final DaoConfig historyDaoConfig;
    private final DaoConfig favoriteDaoConfig;
    private final DaoConfig liveAlertDaoConfig;
    private final DaoConfig playMemoryDaoConfig;

    private final SearchHistoryDao searchHistoryDao;
    private final HistoryDao historyDao;
    private final FavoriteDao favoriteDao;
    private final LiveAlertDao liveAlertDao;
    private final PlayMemoryDao playMemoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);

        historyDaoConfig = daoConfigMap.get(HistoryDao.class).clone();
        historyDaoConfig.initIdentityScope(type);

        favoriteDaoConfig = daoConfigMap.get(FavoriteDao.class).clone();
        favoriteDaoConfig.initIdentityScope(type);

        liveAlertDaoConfig = daoConfigMap.get(LiveAlertDao.class).clone();
        liveAlertDaoConfig.initIdentityScope(type);

        playMemoryDaoConfig = daoConfigMap.get(PlayMemoryDao.class).clone();
        playMemoryDaoConfig.initIdentityScope(type);

        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        historyDao = new HistoryDao(historyDaoConfig, this);
        favoriteDao = new FavoriteDao(favoriteDaoConfig, this);
        liveAlertDao = new LiveAlertDao(liveAlertDaoConfig, this);
        playMemoryDao = new PlayMemoryDao(playMemoryDaoConfig, this);

        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(History.class, historyDao);
        registerDao(Favorite.class, favoriteDao);
        registerDao(LiveAlert.class, liveAlertDao);
        registerDao(PlayMemory.class, playMemoryDao);
    }
    
    public void clear() {
        searchHistoryDaoConfig.getIdentityScope().clear();
        historyDaoConfig.getIdentityScope().clear();
        favoriteDaoConfig.getIdentityScope().clear();
        liveAlertDaoConfig.getIdentityScope().clear();
        playMemoryDaoConfig.getIdentityScope().clear();
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

    public HistoryDao getHistoryDao() {
        return historyDao;
    }

    public FavoriteDao getFavoriteDao() {
        return favoriteDao;
    }

    public LiveAlertDao getLiveAlertDao() {
        return liveAlertDao;
    }

    public PlayMemoryDao getPlayMemoryDao() {
        return playMemoryDao;
    }

}
