package com.cmcc.migutvtwo.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table LIVE_ALERT.
 */
public class LiveAlert {

    private String id;
    private String num;
    private String date;
    private String time;
    private String title;
    private String contid;
    private String liveName;
    private String extend1;
    private java.util.Date alert_time;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public LiveAlert() {
    }

    public LiveAlert(String id) {
        this.id = id;
    }

    public LiveAlert(String id, String num, String date, String time, String title, String contid, String liveName, String extend1, java.util.Date alert_time) {
        this.id = id;
        this.num = num;
        this.date = date;
        this.time = time;
        this.title = title;
        this.contid = contid;
        this.liveName = liveName;
        this.extend1 = extend1;
        this.alert_time = alert_time;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getNum() {
        return num;
    }

    public void setNum(String num) {
        this.num = num;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getContid() {
        return contid;
    }

    public void setContid(String contid) {
        this.contid = contid;
    }

    public String getLiveName() {
        return liveName;
    }

    public void setLiveName(String liveName) {
        this.liveName = liveName;
    }

    public String getExtend1() {
        return extend1;
    }

    public void setExtend1(String extend1) {
        this.extend1 = extend1;
    }

    public java.util.Date getAlert_time() {
        return alert_time;
    }

    public void setAlert_time(java.util.Date alert_time) {
        this.alert_time = alert_time;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
